"""initial schema

Revision ID: 79868cfdf94a
Revises: 
Create Date: 2026-05-11 08:41:59.006792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79868cfdf94a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beliefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('short_id', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cruxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cruxes_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('source_entry_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beliefs_short_id'), 'beliefs', ['short_id'], unique=True)
    op.create_index(op.f('ix_beliefs_topic'), 'beliefs', ['topic'], unique=False)
    op.create_index(op.f('ix_beliefs_updated_at'), 'beliefs', ['updated_at'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_created_at'), 'entries', ['created_at'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dependent', sa.String(length=36), nullable=False),
    sa.Column('depends_on', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['dependent'], ['beliefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on'], ['beliefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_dependent'), 'dependencies', ['dependent'], unique=False)
    op.create_index('ix_dependencies_dependent_kind', 'dependencies', ['dependent', 'kind'], unique=False)
    op.create_index(op.f('ix_dependencies_depends_on'), 'dependencies', ['depends_on'], unique=False)
    op.create_index('ix_dependencies_depends_on_kind', 'dependencies', ['depends_on', 'kind'], unique=False)
    op.create_index(op.f('ix_dependencies_kind'), 'dependencies', ['kind'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('belief_id', sa.String(length=36), nullable=False),
    sa.Column('short_id', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('prev_confidence', sa.Integer(), nullable=True),
    sa.Column('new_confidence', sa.Integer(), nullable=True),
    sa.Column('related_belief_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['beliefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_belief_id'), 'revisions', ['belief_id'], unique=False)
    op.create_index(op.f('ix_revisions_created_at'), 'revisions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_created_at'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_belief_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_dependencies_kind'), table_name='dependencies')
    op.drop_index('ix_dependencies_depends_on_kind', table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_depends_on'), table_name='dependencies')
    op.drop_index('ix_dependencies_dependent_kind', table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_dependent'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_entries_created_at'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_beliefs_updated_at'), table_name='beliefs')
    op.drop_index(op.f('ix_beliefs_topic'), table_name='beliefs')
    op.drop_index(op.f('ix_beliefs_short_id'), table_name='beliefs')
    op.drop_table('beliefs')
    # ### end Alembic commands ###
